version: '3'
services:
  nexus:
    image: sonatype/nexus3
    container_name: nexus3
    restart: always
    ports:
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
      - "8084:8084"
      - "8085:8085"
#    volumes:
#      - /opt/nexus-data:/nexus-data/sonatype/nexus3
