version: '3'
services:
  scrapyd:
    image: scrapyd:1.0
    container_name: scrapyd
    restart: always
    build:
      context: .
      dockerfile: scrapyd/Dockerfile
    ports:
      - "6800:6800"

  scrapydweb:
    image: scrapydweb:1.0
    container_name: scrapydweb123
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - scrapyd