version: '3'
services:
  scrapydweb:
    image: scrapydweb:1.0
    container_name: scrapydweb
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6800:6800"
#      - "5000:5000"
