version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=123"

  redis:
    image: redis
    container_name: redis
    restart: always
    command: redis-server --requirepass 123
    ports:
      - 6379:6379

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123

  rabbitmq:
    image: rabbitmq:3.7-management-alpine
    container_name: rabbitmq
    restart: always
    ports:
      - "15673:15672"
      - "5673:5672"