version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
    volumes:
      - /c/dockerPath/elk/elasticsearch/config/:/usr/share/elasticsearch/config/
      - /c/dockerPath/elk/elasticsearch/data/:/usr/share/elasticsearch/data/
      - /c/dockerPath/elk/elasticsearch/logs/:/usr/share/elasticsearch/logs/

  kibana:
    image: docker.elastic.co/kibana/kibana:7.2.0
    container_name: kibana
    ports:
      - "5601:5601"
    volumes:
      - /c/dockerPath/elk/kibana/config/:/usr/share/kibana/config/
    links:
      - "elasticsearch"
    depends_on:
      - elasticsearch

  logstash:
    image: docker.elastic.co/logstash/logstash:7.2.0
    container_name: logstash
    ports:
      - "9600:9600"
      - "5043:5043"
      - "5044:5044"
    volumes:
      - /c/dockerPath/elk/logstash/config/:/usr/share/logstash/config/
    links:
      - "elasticsearch"
    depends_on:
      - elasticsearch
      - kibana