version: '3'
services:
  elasticsearch:
    image: elasticsearch:1.0
    container_name: elasticsearch
    restart: always
    build:
      context: .
      dockerfile: config/elasticsearch/Dockerfile
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
  #    volumes:
  #      - /home/es/data/:/usr/share/elasticsearch/data/
  #      - /home/es/logs/:/usr/share/elasticsearch/logs/

  kibana:
    image: kibana:1.0
    container_name: kibana
    restart: always
    build:
      context: .
      dockerfile: config/kibana/Dockerfile
    ports:
      - "5601:5601"
    links:
      - "elasticsearch"
    depends_on:
      - elasticsearch

  logstash:
    image: logstash:1.0
    container_name: logstash
    restart: always
    build:
      context: .
      dockerfile: config/logstash/Dockerfile
    ports:
      - "9600:9600"
      - "5043:5043"
      - "5044:5044"
    links:
      - "elasticsearch"
    depends_on:
      - elasticsearch
      - kibana