version: '3'
services:
  redis:
    image: redis:5-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes", "--requirepass","123456"]
